# Site settings
title: LJQ Blog
SEOTitle: 李金泉的博客 | LJQ Blog
header-img: img/home-bg-2.jpg
email: 1464435332@qq.com
description: "Live beautifully,dream passionately,love completely"
keyword: "LJQ, LJQ Blog, 李金泉的博客, lijinquan, 李金泉, JAVA, JAVAWEB, SpringCloud, Docker, SpringBoot, 分布式
,Mybatis-Plus集成pagehelper, centos7安装java，centos7安装maven，Jenkins+docker持续集成开发环境，Spring Cloud eureka，
Spring Cloud，SpringBoot集成swagger"
url: "http://LiJinQ.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/LiJinQ/LiJinQ.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Success is the ability to go from one failure to another with no loss of enthusiasm!"
sidebar-avatar: /img/about-LJQ-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username:    LiJinQ
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 91e48521c61302050943                            #生成的clientID
  clientSecret: b1b0bc0dc7d425f8b257052c18f2395401f222b8    #生成的clientSecret
  repo: LiJinQ.github.io    #仓库名称
  owner: LiJinQ    #github用户名
  admin: LiJinQ
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 1f60d69cf1161671d2febaa066d9d53a

# Google Analytics
ga_track_id: 'UA-131024931-1'            # Format: UA-xxxxxx-xx
ga_domain: www.lijinquan.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Lei Yuan",
        href: "https://imlcl.store"
    },
    {
        title: "Acceleactor",
        href: "https://me.csdn.net/Acceleactor"
    },
    {
        title: "莫烦PYTHON",
        href: "https://morvanzhou.github.io/tutorials/machine-learning/"
    },
    {
        title: "方志朋的博客",
        href: "https://www.fangzhipeng.com/"
    }
]
